words = [
    "Neovim's",
    "autocmd",
    "autocmds",
    "autocommands",
    "bufhidden",
    "buflisted",
    "buftype",
    "devicons",
    "esc",
    "fd's",
    "keymaps",
    "metatable",
    "mkdir",
    "neovim",
    "netrw",
    "noplugin",
    "nvim",
    "patrickswijgman",
    "rawset",
    "rtp",
    "trimempty",
    "virt",
]
